## Please follow the below structure while attempting the hackathon, make sure to submit only one jupyter file with all the models, and you can always mention your best model by giving it the header as 'Best Model'.

## Please make sure to maintain the clarity of analysis in the notebook with proper headers and inisghts/inferences, so that it can be interpretable 


## Please follow the same format as mentioned below, as you will be evaluated basis on your Jupyter Notebook for L2 selection.

## Importing Necessary Libraries

In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.float_format', lambda x: '%.5f' % x)

## 1 Data Cleaning

In this section you can do all the Data cleaning part of all necessary imputations and treatments























In [3]:
data1 = pd.read_csv("Data_Train.csv")
data2 = pd.read_csv("Data_Test.csv")

In [4]:
data1.head(2)

ID  Asst_Reg GGGrade Experience       Validation  Yearly Income  \
0   95074    421802      II     >10yrs            Vfied   633600.00000   
1  134131   3964312      IV       7yrs  Source Verified    85483.20000   

  Home Status  Unpaid 2 years  Already Defaulted       Designation  ...  \
0    MOR??AGE               0                  0   GLENDALE NISSAN  ...   
1        REN?               0                  0  Business Teacher  ...   

   File Status       State  Account Open  Total Unpaid CL  Duration  \
0   fully paid  California            17      58598.00000   3 years   
1        whole          NC            15      18924.00000   5 years   

   Unpaid Amount               Reason  Claim Type  Due Fee  Loan/No Loan  
0    31216.05000  debt  consolidation           I  0.00000             0  
1    11660.49000  debt  consolidation           I  0.00000             0  

[2 rows x 30 columns]

In [5]:
data2.head(2)

ID  Asst_Reg GGGrade Experience       Validation  Yearly Income  \
0  198980   1773284      II       2yrs  Source Verified   140800.00000   
1  167688   5298273      II     >10yrs            Vfied   146080.00000   

  Home Status  Unpaid 2 years  Already Defaulted                  Designation  \
0         OWN               0                  0                    processor   
1    MOR??AGE               0                  0  Speech Language Pathologist   

   ...  Sub GGGrade  File Status       State  Account Open  Total Unpaid CL  \
0  ...           17   fully paid  California            23      33532.00000   
1  ...           19        whole     Florida            17     149234.00000   

   Duration  Unpaid Amount               Reason  Claim Type  Due Fee  
0   3 years    15755.94000      major  purchase           I  0.00000  
1   5 years    68237.55000  debt  consolidation           I  0.00000  

[2 rows x 29 columns]

In [6]:
data1.dtypes

ID                       int64
Asst_Reg                 int64
GGGrade                 object
Experience              object
Validation              object
Yearly Income          float64
Home Status             object
Unpaid 2 years           int64
Already Defaulted        int64
Designation             object
Debt to Income         float64
Postal Code            float64
Lend Amount            float64
Deprecatory Records      int64
Interest Charged       float64
Usage Rate             float64
Inquiries                int64
Present Balance        float64
Gross Collection       float64
Sub GGGrade              int64
File Status             object
State                   object
Account Open             int64
Total Unpaid CL        float64
Duration                object
Unpaid Amount          float64
Reason                  object
Claim Type              object
Due Fee                float64
Loan/No Loan             int64
dtype: object

In [7]:
data2.dtypes

ID                       int64
Asst_Reg                 int64
GGGrade                 object
Experience              object
Validation              object
Yearly Income          float64
Home Status             object
Unpaid 2 years           int64
Already Defaulted        int64
Designation             object
Debt to Income         float64
Postal Code            float64
Lend Amount            float64
Deprecatory Records      int64
Interest Charged       float64
Usage Rate             float64
Inquiries                int64
Present Balance        float64
Gross Collection       float64
Sub GGGrade              int64
File Status             object
State                   object
Account Open             int64
Total Unpaid CL        float64
Duration                object
Unpaid Amount          float64
Reason                  object
Claim Type              object
Due Fee                float64
dtype: object

In [8]:
# Checking whether dataframe columns are equal or not
dataframes = [data1, data2]

# Checking all dataframe columns, whether they are equal or not
if all([len(dataframes[0].columns.intersection(df.columns)) 
      == dataframes[0].shape[1] for df in dataframes]) == True:
    print("The dataframes have same column names")
else:
    print("The dataframes does not have same column names")

The dataframes does not have same column names


In [9]:
# Finding column differences
tr_cols = data1.columns
te_cols = data2.columns
print(tr_cols.difference(te_cols))
print(te_cols.difference(tr_cols))

Index(['Loan/No Loan'], dtype='object')
Index([], dtype='object')


In [10]:
data1.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation            1414
Debt to Income         3489
Postal Code            1389
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        4186
Duration                  0
Unpaid Amount          4852
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [11]:
data2.isnull().sum()

ID                        0
Asst_Reg                  0
GGGrade                   0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Designation             586
Debt to Income         1511
Postal Code             611
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
Sub GGGrade               0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Claim Type                0
Due Fee                   0
dtype: int64

In [12]:
data1.shape

(87500, 30)

In [13]:
data2.shape

(37500, 29)

In [14]:
# Checking set of values in all columns
for i in data1.columns:
    print("\nValues for ", i)
    print(data1[i].unique())


Values for  ID
[ 95074 134131  92602 ... 102153 115343 104968]

Values for  Asst_Reg
[ 421802 3964312 4247560 ... 2624710 5966919 6637289]

Values for  GGGrade
['II' 'IV' 'III' 'V' 'VII' 'VI' 'I']

Values for  Experience
['>10yrs' '7yrs' '<1yr' '2yrs' '1yrs' '4yrs' '9yrs' '6yrs' '5yrs' '8yrs'
 '3yrs']

Values for  Validation
['Vfied' 'Source Verified' 'Not Vfied']

Values for  Yearly Income
[633600.    85483.2   79200.   ... 510398.24 154191.84  90423.52]

Values for  Home Status
['MOR??AGE' 'REN?' 'OWN' 'OTHER' 'NONE']

Values for  Unpaid 2 years
[ 0  4  2  1  3 11  5  6  7  9 12  8 10 18 16 15 13 14]

Values for  Already Defaulted
[0 1 2 6 5 4 3]

Values for  Designation
['GLENDALE NISSAN' 'Business Teacher' 'driver' ... 'Interface Coordinator'
 'PARTS CLERK' 'Outside sales rep']

Values for  Debt to Income
[12.5496  9.0048 24.9144 ... 65.7216  0.4032 63.6888]

Values for  Postal Code
[91300. 27400. 32800.  7000. 70800. 77000. 92100.  6000. 92500. 78500.
 95900. 49400. 97200. 72200.

[ 58598.    18924.    15604.   ... 495510.    27456.4  105859.86]

Values for  Duration
['3 years' '5 years']

Values for  Unpaid Amount
[31216.05 11660.49  5637.87 ... 82601.55 82056.06 52676.55]

Values for  Reason
['debt  consolidation' 'major  purchase' 'other' 'credit  card' 'car'
 'home  improvement' 'small  business' 'moving' 'vacation' 'medical'
 'wedding' 'house' 'renewable  energy']

Values for  Claim Type
['I' 'J']

Values for  Due Fee
[0.00000000e+00 1.50000000e+01 1.50000001e+01 2.81200000e+01
 5.97600000e+01 5.06200000e+01 4.31200000e+01 3.38800000e+01
 1.88400000e+01 3.99582903e+01 2.82625006e+01 3.81600000e+01
 2.57500000e+01 2.33100000e+01 2.54300000e+01 3.16100000e+01
 1.76300000e+01 4.67400000e+01 2.15600000e+01 4.10200000e+01
 2.16300000e+01 1.84000000e+01 4.92700000e+01 1.72100000e+01
 2.71100000e+01 1.63700000e+01 3.67200000e+01 3.62400000e+01
 9.94000000e+01 3.00000000e+01 2.11900000e+01 3.76045674e+01
 5.40700000e+01 1.56000000e+01 4.40700000e+01 3.38500000e+01


In [15]:
# Checking set of values in all columns
for i in data2.columns:
    print("\nValues for ", i)
    print(data2[i].unique())


Values for  ID
[198980 167688 198768 ... 163156 169610 175557]

Values for  Asst_Reg
[1773284 5298273  189781 ... 1895531 2168910 4140268]

Values for  GGGrade
['II' 'VI' 'III' 'V' 'IV' 'I' 'VII']

Values for  Experience
['2yrs' '>10yrs' '4yrs' '9yrs' '1yrs' '<1yr' '3yrs' '5yrs' '8yrs' '7yrs'
 '6yrs']

Values for  Validation
['Source Verified' 'Vfied' 'Not Vfied']

Values for  Yearly Income
[140800.    146080.    202222.24  ... 263577.6   171508.48   96718.336]

Values for  Home Status
['OWN' 'MOR??AGE' 'REN?' 'NONE' 'OTHER']

Values for  Unpaid 2 years
[ 0  1  2  4  3  5  7 10 12 15  6  8 17  9 14 13 11 18]

Values for  Already Defaulted
[0 1 2 3]

Values for  Designation
['processor' 'Speech Language Pathologist' 'Raytheon' ...
 'Parade Performer' 'Sr. Chemistry Technician' 'ParaEducator']

Values for  Debt to Income
[16.9176 28.6944 51.156  ...  2.604  66.8808 64.9992]

Values for  Postal Code
[90600. 32300. 88000. 19900. 34900. 10400. 62000.    nan  3200. 65400.
 18600. 48000. 460

In [16]:
# Checking for data imbalance
data1["Loan/No Loan"].value_counts()

0    70988
1    16512
Name: Loan/No Loan, dtype: int64

Data is highly imbalanced

In [17]:
# Dropping irrelevant columns
df1 = data1.drop(["GGGrade", "Sub GGGrade", "Postal Code", "Designation"], axis = 1)
df2 = data2.drop(["GGGrade", "Sub GGGrade", "Postal Code", "Designation"], axis = 1)

In [18]:
df1["Home Status"] = df1["Home Status"].replace("MOR??AGE", "MORTGAGE")
df1["Home Status"] = df1["Home Status"].replace("REN?", "RENT")

df2["Home Status"] = df2["Home Status"].replace("MOR??AGE", "MORTGAGE")
df2["Home Status"] = df2["Home Status"].replace("REN?", "RENT")

In [19]:
df1.describe()

ID      Asst_Reg  Yearly Income  Unpaid 2 years  \
count  87500.00000   87500.00000    81925.00000     87500.00000   
mean   83946.25351 3798914.12415   134859.62978         0.33294   
std    36100.10295 2289038.08259    98824.72556         0.87608   
min    21560.00000   24847.00000     8800.00000         0.00000   
25%    52616.75000 1483874.25000    83246.59200         0.00000   
50%    83900.00000 4132010.50000   114400.00000         0.00000   
75%   115261.25000 5952908.75000   160160.00000         0.00000   
max   146559.00000 7351847.00000  8264030.72000        18.00000   

       Already Defaulted  Debt to Income  Lend Amount  Deprecatory Records  \
count        87500.00000     84011.00000  87500.00000          87500.00000   
mean             0.00573        30.94266  25920.53568              0.20240   
std              0.08350        14.07981  14433.83721              0.64641   
min              0.00000         0.00000   1710.00000              0.00000   
25%              0.00000        20.42880  15048.00000              0.00000   
50%              0.00000        30.13920  23940.00000              0.00000   
75%              0.00000        40.90800  34200.00000              0.00000   
max              6.00000       639.29040  59850.00000             86.00000   

       Interest Charged  Usage Rate   Inquiries  Present Balance  \
count       87500.00000 87500.00000 87500.00000      87500.00000   
mean           16.51837    95.51735     0.67064     236389.46478   
std             4.90201    40.55404     0.95957     255056.78191   
min             8.00000     0.00000     0.00000          0.00000   
25%            12.31000    66.04800     0.00000      51734.93000   
50%            16.49000    97.00800     0.00000     138806.22500   
75%            20.77000   126.59200     1.00000     353475.54000   
max            25.00000  1534.75600     8.00000    5629234.33000   

       Gross Collection  Account Open  Total Unpaid CL  Unpaid Amount  \
count       87500.00000   87500.00000      83314.00000    82648.00000   
mean           39.46170      12.77944      53268.64039    29556.49452   
std           391.91958       5.37116      53255.51391    37456.24506   
min             0.00000       2.00000        332.00000        0.00000   
25%             0.00000       9.00000      23240.00000    11446.74000   
50%             0.00000      12.00000      39674.00000    20892.78000   
75%             0.00000      16.00000      66400.00000    36449.07750   
max         26308.47000      83.00000    1710630.00000  1338777.81000   

          Due Fee  Loan/No Loan  
count 87500.00000   87500.00000  
mean      0.31641       0.18871  
std       3.54609       0.39128  
min       0.00000       0.00000  
25%       0.00000       0.00000  
50%       0.00000       0.00000  
75%       0.00000       0.00000  
max     169.05000       1.00000

In [20]:
df2.describe()

ID      Asst_Reg  Yearly Income  Unpaid 2 years  \
count  37500.00000   37500.00000    35075.00000     37500.00000   
mean  184143.86797 3804857.79483   134030.83240         0.33643   
std    21683.22439 2284114.95103   100084.49663         0.88764   
min   146560.00000   37522.00000     8800.00000         0.00000   
25%   165341.25000 1495828.50000    84194.00000         0.00000   
50%   184257.00000 4134009.50000   114400.00000         0.00000   
75%   202869.25000 5934897.75000   158400.00000         0.00000   
max   221557.00000 7351969.00000  8800000.00000        18.00000   

       Already Defaulted  Debt to Income  Lend Amount  Deprecatory Records  \
count        37500.00000     35989.00000  37500.00000          37500.00000   
mean             0.00531        30.91903  25828.00416              0.20008   
std              0.07797        13.87167  14402.06179              0.56314   
min              0.00000         0.00000   1710.00000              0.00000   
25%              0.00000        20.47920  14919.75000              0.00000   
50%              0.00000        30.18960  23811.75000              0.00000   
75%              0.00000        40.72320  34200.00000              0.00000   
max              3.00000       116.50800  59850.00000             21.00000   

       Interest Charged  Usage Rate   Inquiries  Present Balance  \
count       37500.00000 37500.00000 37500.00000      37500.00000   
mean           16.51101    95.25911     0.67664     235352.80234   
std             4.91259    40.49322     0.96452     254309.73318   
min             8.00000     0.00000     0.00000          0.00000   
25%            12.25000    65.53200     0.00000      51295.72000   
50%            16.51500    96.49200     0.00000     138379.54000   
75%            20.77000   126.76400     1.00000     351498.26000   
max            25.00000   254.56000     6.00000    4909890.18000   

       Gross Collection  Account Open  Total Unpaid CL  Unpaid Amount  \
count       37500.00000   37500.00000      35686.00000    35431.00000   
mean           39.48407      12.77779      53448.19734    29280.65881   
std           364.11458       5.36053      52154.82990    35608.49292   
min             0.00000       2.00000        332.00000        0.00000   
25%             0.00000       9.00000      23240.00000    11414.25000   
50%             0.00000      12.00000      39508.00000    20680.74000   
75%             0.00000      15.00000      66400.00000    36184.45500   
max         13900.00000      60.00000    1475408.00000  1535829.66000   

          Due Fee  
count 37500.00000  
mean      0.30979  
std       3.39632  
min       0.00000  
25%       0.00000  
50%       0.00000  
75%       0.00000  
max     131.49000

In [21]:
up_quan = df1["Yearly Income"].quantile(.75)
low_quan = df1["Yearly Income"].quantile(.25)
low_bound = 1.5 * low_quan
up_bound = 1.5 * up_quan
index_names = df1[ (df1['Yearly Income'] < low_bound) | (df1['Yearly Income'] > up_bound) ].index
df1.drop(index_names, inplace = True)
low_bound, up_bound, index_names

(124869.888,
 240240.0,
 Int64Index([    0,     1,     2,     3,     4,     6,    10,    13,    14,
                15,
             ...
             87484, 87486, 87489, 87490, 87493, 87494, 87495, 87496, 87497,
             87498],
            dtype='int64', length=52951))

In [22]:
df1.isnull().sum()

ID                        0
Asst_Reg                  0
Experience                0
Validation                0
Yearly Income          5575
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1359
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1684
Duration                  0
Unpaid Amount          1903
Reason                    0
Claim Type                0
Due Fee                   0
Loan/No Loan              0
dtype: int64

In [23]:
df2.isnull().sum()

ID                        0
Asst_Reg                  0
Experience                0
Validation                0
Yearly Income          2425
Home Status               0
Unpaid 2 years            0
Already Defaulted         0
Debt to Income         1511
Lend Amount               0
Deprecatory Records       0
Interest Charged          0
Usage Rate                0
Inquiries                 0
Present Balance           0
Gross Collection          0
File Status               0
State                     0
Account Open              0
Total Unpaid CL        1814
Duration                  0
Unpaid Amount          2069
Reason                    0
Claim Type                0
Due Fee                   0
dtype: int64

In [24]:
df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']] = df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].fillna(df1[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].median())
df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']] = df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].fillna(df2[['Yearly Income', 'Debt to Income', 'Total Unpaid CL', 'Unpaid Amount']].median())

In [25]:
stru = {
        "Experience" : {"<1yr": 0, "1yrs": 1, "2yrs": 2, "3yrs": 3, "4yrs": 4, "5yrs": 5, "6yrs": 6, "7yrs": 7, "8yrs": 8, "9yrs": 9, ">10yrs": 10 },
        "Validation" : {"Not Vfied": 0, "Vfied": 1, "Source Verified": 2},
        "Home Status" : {"NONE": 0, "RENT": 1,"MORTGAGE": 2, "OWN": 3, "OTHER": 4},
        "File Status" : {"whole": 0, "fully paid": 1},
        "Duration" : {"3 years": 0, "5 years": 1},
        "Claim Type" : {"I": 0, "J": 1}
        }

# Columns for One Hot Encoding

oneHotCols=["State", "Reason"]

# Performing Label Encoding

df1 = df1.replace(stru)
df2 = df2.replace(stru)


# Performing One Hot Encoding

df1 = pd.get_dummies(df1, oneHotCols)
df2 = pd.get_dummies(df2, oneHotCols)

## 2 Exploratory Data Analyis

In this section you can talk about the plots and the insights you have generated from the data

























## 3 Feature Engineering

In this section you can implement the feature engineering techniques for dimensionality reduction












In [26]:
# Train-test Split
from sklearn.model_selection import train_test_split

x = df1.drop("Loan/No Loan", axis = 1)
y = df1["Loan/No Loan"]

x_tr, x_val, y_tr, y_val = train_test_split(x, y, test_size = .3, random_state = 9)

In [27]:
x_tr = x_tr.astype("float32")
x_val = x_val.astype("float32")
y_tr = y_tr.astype("float32")
y_val = y_val.astype("float32")

In [28]:
# Balancing Classes
from imblearn.over_sampling import SMOTE
sm = SMOTE(sampling_strategy = 1 ,k_neighbors = 15)   #Synthetic Minority Over Sampling Technique
x_tr_res, y_tr_res = sm.fit_resample(x_tr, y_tr.ravel())

In [29]:
# Applying PCA
from sklearn.decomposition import PCA as RandomizedPCA

n_components = 50              # extracting 50 most important features
pca = RandomizedPCA(n_components=n_components).fit(x_tr_res)
x_train_pca = pca.transform(x_tr_res)
x_test_pca = pca.transform(x_val)

In [30]:
# Scaling Data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train_pca)
x_tr = sc.transform(x_train_pca)
x_val = sc.transform(x_test_pca)

## 4 Modelling + HyperParameter Tuning

In this you can build various ML models and try tuning the parameters involved to achieve better score

## Model 1

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(max_iter = 400)

param_lr = {"solver" : ["newton-cg", "lbfgs", "liblinear"]}

gs_lr = GridSearchCV(lr, param_lr, cv=10)

gs_lr.fit(x_tr, y_tr_res)
print(gs_lr.score(x_tr, y_tr_res))
lr_pr = gs_lr.predict(x_val)
print("F1 Score: ", f1_score(y_val,lr_pr))

C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')
C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserW

0.755834829443447
F1 Score:  0.5262072521051727


C:\ProgramData\Anaconda3\lib\site-packages\scipy\optimize\linesearch.py:327: LineSearchWarning: The line search algorithm did not converge
  warn('The line search algorithm did not converge', LineSearchWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\optimize.py:195: UserWarning: Line Search failed
  warnings.warn('Line Search failed')


In [32]:
from sklearn.neighbors import KNeighborsClassifier

#knn = KNeighborsClassifier()

#param_knn = {"n_neighbors": range(3,11),
#            "weights" : ["uniform", "distance"],
#             "algorithm" : ["auto", "ball_tree", "kd_tree", "brute"]}

gs_knn = KNeighborsClassifier(n_neighbors = 15, weights = "uniform", algorithm = "auto")
gs_knn.fit(x_tr, y_tr_res)
knn_pr = gs_knn.predict(x_val)
print(gs_knn.score(x_val, y_val))
print(f1_score(y_val, knn_pr))

0.6878919440424506
0.4163810211077034


In [33]:
from sklearn import svm
gs_svm = svm.SVC(C = 3, gamma = .3, kernel = "rbf" ) 
#param_grid = {"C": range(1, 11),
#              "gamma": [0.3, 0.4, 0.5],
#              "kernel": ["rbf", "poly", "sigmoid", "linear"]}

#gs_svm = GridSearchCV(clf, param_grid, cv=10)

gs_svm.fit(x_tr, y_tr_res)
svm_pr = gs_svm.predict(x_val)
print(gs_svm.score(x_val, y_val))
print(f1_score(y_val, svm_pr))

0.8060781476121563
0.09459459459459459


In [34]:
from sklearn.tree import DecisionTreeClassifier
gs_dt = DecisionTreeClassifier(criterion = "gini", max_depth = 12)

#param_dt = {"criterion" : ["gini", "entropy"],
#             "max_depth" : [11, 12, 13]}
#gs_dt = GridSearchCV(dt, param_dt, cv=10)
gs_dt.fit(x_tr, y_tr_res)
dt_pr = gs_dt.predict(x_val)
print(gs_dt.score(x_val, y_val))
print(f1_score(y_val, dt_pr))

0.704003859141341
0.44800287873335737


In [35]:
from sklearn.ensemble import RandomForestClassifier

gs_rf = RandomForestClassifier(criterion = "gini", max_depth = 12, n_estimators = 60)

#param_rf = {"criterion" : ["gini", "entropy"],
#             "max_depth" : range(1, 15),
#           "n_estimators" : [10, 20, 30, 40, 50, 60]}
#gs_rf = GridSearchCV(rf, param_rf, cv=10)
gs_rf.fit(x_tr, y_tr_res)
print(gs_rf.score(x_val, y_val))
rtr_pr = gs_rf.predict(x_val)
print(f1_score(y_val, rtr_pr))

0.7579353593825374
0.5185185185185185


In [41]:
df2 = df2.drop("Loan/No Loan", axis = 1)
x_test = pd.DataFrame(df2)
x_test.head()
x_test = pca.transform(x_test)
x_test = sc.transform(x_test)
x_test = pd.DataFrame(x_test)
x_test = x_test.replace((np.inf, -np.inf, np.nan), 0).reset_index(drop=True)
test_pre = gs_lr.predict(x_test)

In [42]:
df2["Loan/No Loan"] = test_pre

In [43]:
df = pd.DataFrame(df2[["ID","Loan/No Loan"]])

In [44]:
df.to_csv("res.csv", index = False)

## Model 2 - Best Model

## Model 3